name: Zip repository
on: [workflow_dispatch]

jobs:
  zip:
    name: Zip
    runs-on: ubuntu-latest
    steps:
      - name: Zip Folder
        run: |
          cd ../ 
          rm -rf RecipeTweaks.zip
          zip -r RecipeTweaks.zip . -i data/ pack.mcmeta

