name: Zip repository
on: [workflow_dispatch]

jobs:
  zip:
    name: Zip
    runs-on: ubuntu-latest
    steps:
      - name: Zip Folder
        run: |
          cd ../ 
          rm -rf <repository_name>.zip
          zip -r <repository_name>.zip <repository_name> -x ".git/*" ".github/*"

